// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TotemPWA.Data;

#nullable disable

namespace TotemPWA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250713213121_refix")]
    partial class refix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("TotemPWA.Models.Adicional", b =>
                {
                    b.Property<int>("AdicionalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IgredienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItensPedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdicionalId");

                    b.HasIndex("IgredienteId");

                    b.HasIndex("ItensPedidoId");

                    b.ToTable("Adicionais");
                });

            modelBuilder.Entity("TotemPWA.Models.Administrador", b =>
                {
                    b.Property<int>("AdministradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AdministradorId");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("TotemPWA.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Banner")
                        .HasColumnType("BLOB");

                    b.Property<int?>("CategoriaPaiId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriaId");

                    b.HasIndex("CategoriaPaiId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("TotemPWA.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Pontos")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("TotemPWA.Models.Cupom", b =>
                {
                    b.Property<int>("CupomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdministradorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Desconto")
                        .HasColumnType("REAL");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Validade")
                        .HasColumnType("TEXT");

                    b.HasKey("CupomId");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Cupons");
                });

            modelBuilder.Entity("TotemPWA.Models.Igrediente", b =>
                {
                    b.Property<int>("IgredienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Imagem")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("IgredienteId");

                    b.ToTable("Igredientes");
                });

            modelBuilder.Entity("TotemPWA.Models.IgredienteProduto", b =>
                {
                    b.Property<int>("IgredienteProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IgredienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Quantidade")
                        .HasColumnType("REAL");

                    b.HasKey("IgredienteProdutoId");

                    b.HasIndex("IgredienteId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("IgredienteProdutos");
                });

            modelBuilder.Entity("TotemPWA.Models.ItensCombo", b =>
                {
                    b.Property<int>("ItensComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CupomId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CupomId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProdutoId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItensComboId");

                    b.HasIndex("CupomId");

                    b.HasIndex("CupomId1")
                        .IsUnique();

                    b.HasIndex("ProdutoId");

                    b.HasIndex("ProdutoId1");

                    b.ToTable("ItensCombos");
                });

            modelBuilder.Entity("TotemPWA.Models.ItensPedido", b =>
                {
                    b.Property<int>("ItensPedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItensPedidoId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensPedidos");
                });

            modelBuilder.Entity("TotemPWA.Models.Pagamento", b =>
                {
                    b.Property<int>("PagamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("PagamentoId");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("TotemPWA.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PagamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("PedidoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("TotemPWA.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdministradorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Imagem")
                        .HasColumnType("BLOB");

                    b.Property<int>("IsCombo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("ProdutoId");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("TotemPWA.Models.Adicional", b =>
                {
                    b.HasOne("TotemPWA.Models.Igrediente", "Igrediente")
                        .WithMany("Adicionais")
                        .HasForeignKey("IgredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TotemPWA.Models.ItensPedido", "ItensPedido")
                        .WithMany("Adicionais")
                        .HasForeignKey("ItensPedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igrediente");

                    b.Navigation("ItensPedido");
                });

            modelBuilder.Entity("TotemPWA.Models.Categoria", b =>
                {
                    b.HasOne("TotemPWA.Models.Categoria", "CategoriaPai")
                        .WithMany("Subcategorias")
                        .HasForeignKey("CategoriaPaiId");

                    b.Navigation("CategoriaPai");
                });

            modelBuilder.Entity("TotemPWA.Models.Cupom", b =>
                {
                    b.HasOne("TotemPWA.Models.Administrador", "Administrador")
                        .WithMany("Cupons")
                        .HasForeignKey("AdministradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TotemPWA.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrador");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("TotemPWA.Models.IgredienteProduto", b =>
                {
                    b.HasOne("TotemPWA.Models.Igrediente", "Igrediente")
                        .WithMany("IgredienteProdutos")
                        .HasForeignKey("IgredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TotemPWA.Models.Produto", "Produto")
                        .WithMany("IgredienteProdutos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igrediente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("TotemPWA.Models.ItensCombo", b =>
                {
                    b.HasOne("TotemPWA.Models.Cupom", "Cupom")
                        .WithMany()
                        .HasForeignKey("CupomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TotemPWA.Models.Cupom", null)
                        .WithOne("ItensCombo")
                        .HasForeignKey("TotemPWA.Models.ItensCombo", "CupomId1");

                    b.HasOne("TotemPWA.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TotemPWA.Models.Produto", null)
                        .WithMany("ItensCombo")
                        .HasForeignKey("ProdutoId1");

                    b.Navigation("Cupom");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("TotemPWA.Models.ItensPedido", b =>
                {
                    b.HasOne("TotemPWA.Models.Pedido", "Pedido")
                        .WithMany("ItensPedido")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TotemPWA.Models.Produto", "Produto")
                        .WithMany("ItensPedidos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("TotemPWA.Models.Pagamento", b =>
                {
                    b.HasOne("TotemPWA.Models.Pedido", "Pedido")
                        .WithOne("Pagamento")
                        .HasForeignKey("TotemPWA.Models.Pagamento", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("TotemPWA.Models.Pedido", b =>
                {
                    b.HasOne("TotemPWA.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("TotemPWA.Models.Produto", b =>
                {
                    b.HasOne("TotemPWA.Models.Administrador", "Administrador")
                        .WithMany("Produto")
                        .HasForeignKey("AdministradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TotemPWA.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrador");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("TotemPWA.Models.Administrador", b =>
                {
                    b.Navigation("Cupons");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("TotemPWA.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");

                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("TotemPWA.Models.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("TotemPWA.Models.Cupom", b =>
                {
                    b.Navigation("ItensCombo")
                        .IsRequired();
                });

            modelBuilder.Entity("TotemPWA.Models.Igrediente", b =>
                {
                    b.Navigation("Adicionais");

                    b.Navigation("IgredienteProdutos");
                });

            modelBuilder.Entity("TotemPWA.Models.ItensPedido", b =>
                {
                    b.Navigation("Adicionais");
                });

            modelBuilder.Entity("TotemPWA.Models.Pedido", b =>
                {
                    b.Navigation("ItensPedido");

                    b.Navigation("Pagamento")
                        .IsRequired();
                });

            modelBuilder.Entity("TotemPWA.Models.Produto", b =>
                {
                    b.Navigation("IgredienteProdutos");

                    b.Navigation("ItensCombo");

                    b.Navigation("ItensPedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
